version: "3"
services:
  api:
    container_name: connect
    build:
      context: .
    volumes:
      - ./:/var/task
      - ~/.aws/:/root/.aws:ro
    ports:
      - "8888"
    command: chalice local --host 127.0.0.1 --port 8888 --stage dev --autoreload
